name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Set up Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: '8.0'

    - name: Build APK
      run: gradle assembleRelease

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: android-apk
        path: app/build/outputs/apk/release/

    - name: Build AAB
      run: gradle bundleRelease

    - name: Upload AAB Artifact
      uses: actions/upload-artifact@v4
      with:
        name: android-aab
        path: app/build/outputs/bundle/release/
